"""Report generation: markdown, JSON, strategy cards, scoring helpers.

All strategy card content (cause analysis, action plans, KPIs, ideas)
is generated by LLM. No hardcoded libraries.
"""
from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path
from typing import Any

from .config import (
    AGENT_FINAL_WEIGHTS,
    DEBATE_ROUNDS_DEFAULT,
    FLAT_MODE_AGENTS,
    HIERARCHICAL_FINAL_WEIGHTS,
    LLM_REPORT_SECTION_TIMEOUT_SECONDS,
    ORCHESTRATION_PROFILE_DEFAULT,
    ORCHESTRATION_STAGES_DEFAULT,
    SUBORDINATE_BLEND_DEFAULT,
    _normalize_stages,
)
from .llm_client import run_llm_command
from .types import OrchestrationDecision, TopicState

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Shared topic payload builder (used by all LLM report generators)
# ---------------------------------------------------------------------------

def _build_topic_payload(
    items: list[dict] | dict[str, TopicState],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]] | None = None,
    agent_decisions: dict[str, list[dict]] | None = None,
    max_evidence_snippets: int = 6,
    include_projects: bool = False,
    include_project_hits: bool = False,
    include_code_doc: bool = False,
    include_agent_scores: bool = False,
    include_agent_decisions: bool = False,
    include_evidence_files: bool = False,
) -> list[dict]:
    """Build topic payload dicts from ranked items or all states."""
    result: list[dict] = []
    # Support iterating over ranked list[dict] or all states dict
    if isinstance(items, dict):
        entries = [
            {"topic_id": tid, "topic_name": s.topic_name}
            for tid, s in items.items()
        ]
    else:
        entries = items

    for item in entries:
        topic_id = item["topic_id"]
        state = states.get(topic_id)
        if not state:
            continue
        payload: dict[str, Any] = {
            "topic_id": topic_id,
            "topic_name": item.get("topic_name", state.topic_name),
            "total_score": item.get("total_score", 0),
            "features": item.get("features", {}),
            "evidence_count": len(state.evidence),
            "project_count": state.project_count,
        }
        if include_projects:
            payload["projects"] = sorted(state.project_hits.keys())
        if include_project_hits:
            payload["project_hits"] = dict(state.project_hits)
        if include_code_doc:
            payload["code_hits"] = state.code_hits
            payload["doc_hits"] = state.doc_hits
        snippets = state.evidence[:max_evidence_snippets]
        if include_evidence_files:
            payload["evidence_snippets"] = [
                {"file": e.file, "snippet": e.snippet} for e in snippets
            ]
        else:
            payload["evidence_snippets"] = [e.snippet for e in snippets]
        if include_agent_scores and scores:
            payload["agent_scores"] = scores.get(topic_id, {})
        if include_agent_decisions and agent_decisions:
            payload["agent_decisions"] = agent_decisions.get(topic_id, [])
        result.append(payload)
    return result


# ---------------------------------------------------------------------------
# LLM-driven strategy card generation
# ---------------------------------------------------------------------------

def _build_aggregate_stats(
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]] | None = None,
    research_sources: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Build aggregate statistics for grounding LLM prompts."""
    total_evidence = sum(len(s.evidence) for s in states.values())
    total_code = sum(s.code_hits for s in states.values())
    total_doc = sum(s.doc_hits for s in states.values())
    total_projects = len({p for s in states.values() for p in s.project_hits})
    source_count = len(research_sources or [])
    verified_sources = sum(
        1 for s in (research_sources or []) if s.get("status") == "search_verified"
    )

    score_values: list[float] = []
    if scores:
        for per_topic in scores.values():
            for v in per_topic.values():
                try:
                    score_values.append(float(v))
                except (TypeError, ValueError):
                    pass

    stats: dict[str, Any] = {
        "total_topics": len(states),
        "total_evidence_snippets": total_evidence,
        "total_code_hits": total_code,
        "total_doc_hits": total_doc,
        "unique_projects": total_projects,
        "research_sources_total": source_count,
        "research_sources_verified": verified_sources,
    }
    if score_values:
        stats["score_distribution"] = {
            "min": round(min(score_values), 2),
            "max": round(max(score_values), 2),
            "mean": round(sum(score_values) / len(score_values), 2),
            "count": len(score_values),
        }
    return stats


def generate_strategy_cards_via_llm(
    top_topics: list[dict],
    states: dict[str, TopicState],
    llm_command: str,
    llm_timeout: float = 30.0,
    agent_decisions: dict[str, list[dict]] | None = None,
    sources: list[dict[str, str]] | None = None,
) -> list[dict]:
    """Generate strategy cards entirely via LLM."""
    topics_payload = _build_topic_payload(
        top_topics, states, agent_decisions=agent_decisions,
        include_projects=True, include_agent_decisions=True,
    )

    payload = {
        "version": "llm-strategy-v1",
        "aggregate_stats": _build_aggregate_stats(states, research_sources=sources),
        "output_contract": {
            "strategy_cards": [{
                "topic_id": "string",
                "innovation_ideas": [{"idea": "string", "differentiator": "string", "expected_impact": "string"}],
                "competitive_edge": "string",
                "cause_analysis": ["string"],
                "action_plan": [{"phase": "string", "tasks": ["string"]}],
                "success_metrics": ["string"],
                "expected_impact": "string",
                "risk_mitigation": "string",
            }],
        },
        "topics": topics_payload,
        "research_sources": (sources or [])[:20],
    }

    result = run_llm_command(
        payload=payload,
        command=llm_command,
        timeout=llm_timeout,
    )

    if result.status != "ok":
        logger.warning("LLM strategy card generation failed: %s", result.parsed.get("reason", "unknown"))
        return _build_minimal_cards(top_topics, states, agent_decisions, sources)

    cards_raw = result.parsed.get("strategy_cards", [])
    if not isinstance(cards_raw, list) or not cards_raw:
        logger.warning("LLM returned empty strategy cards")
        return _build_minimal_cards(top_topics, states, agent_decisions, sources)

    cards = []
    for idx, card in enumerate(cards_raw, start=1):
        if not isinstance(card, dict):
            continue
        topic_id = card.get("topic_id", "")
        state = states.get(topic_id)
        if not state:
            continue
        # Find matching item from top_topics
        matched_item = next((item for item in top_topics if item["topic_id"] == topic_id), None)
        cards.append({
            "rank": idx,
            "topic_id": topic_id,
            "topic_name": matched_item["topic_name"] if matched_item else state.topic_name,
            "score": matched_item.get("total_score", 0) if matched_item else 0,
            "feature_profile": matched_item.get("features", {}) if matched_item else {},
            "evidence_count": len(state.evidence),
            "projects": state.project_hits,
            "project_snapshot": _top_projects_summary(state),
            "innovation_ideas": card.get("innovation_ideas", []),
            "competitive_edge": card.get("competitive_edge", ""),
            "cause_analysis": card.get("cause_analysis", []),
            "action_plan": card.get("action_plan", []),
            "success_metrics": card.get("success_metrics", []),
            "expected_impact": card.get("expected_impact", ""),
            "risk_mitigation": card.get("risk_mitigation", ""),
            "agent_decisions": (agent_decisions or {}).get(topic_id, []),
            "evidence_snapshots": [
                {"file": e.file, "line": e.line_no, "snippet": e.snippet}
                for e in state.evidence[:8]
            ],
            "papers": [],
        })
    return cards


def _build_minimal_cards(
    top_topics: list[dict],
    states: dict[str, TopicState],
    agent_decisions: dict[str, list[dict]] | None = None,
    sources: list[dict[str, str]] | None = None,
) -> list[dict]:
    """Minimal card structure when LLM fails (no hardcoded content)."""
    source_map: dict[str, list[dict[str, str]]] = {}
    for item in sources or []:
        key = item.get("topic_id", "")
        source_map.setdefault(key, []).append(item)

    cards: list[dict] = []
    for idx, item in enumerate(top_topics, start=1):
        topic_id = item["topic_id"]
        state = states.get(topic_id)
        if not state:
            continue
        cards.append({
            "rank": idx,
            "topic_id": topic_id,
            "topic_name": item["topic_name"],
            "score": item.get("total_score", 0),
            "feature_profile": item.get("features", {}),
            "evidence_count": len(state.evidence),
            "projects": state.project_hits,
            "project_snapshot": _top_projects_summary(state),
            "innovation_ideas": [],
            "competitive_edge": "",
            "cause_analysis": [],
            "action_plan": [],
            "success_metrics": [],
            "expected_impact": "",
            "risk_mitigation": "",
            "agent_decisions": (agent_decisions or {}).get(topic_id, []),
            "evidence_snapshots": [
                {"file": e.file, "line": e.line_no, "snippet": e.snippet}
                for e in state.evidence[:8]
            ],
            "papers": source_map.get(topic_id, [])[:6],
        })
    return cards


# ---------------------------------------------------------------------------
# LLM-driven QA verification
# ---------------------------------------------------------------------------

def run_qa_verification_via_llm(
    top_topics: list[dict],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    llm_command: str,
    llm_timeout: float = 30.0,
) -> list[dict]:
    """Run QA verification on selected topics via LLM."""
    topics_payload = _build_topic_payload(
        top_topics, states, scores=scores,
        max_evidence_snippets=4, include_code_doc=True, include_agent_scores=True,
    )

    payload = {
        "version": "llm-qa-v1",
        "output_contract": {
            "verification": [{
                "topic_id": "string",
                "passed": "bool",
                "evidence_quality": "0-10",
                "concerns": ["string"],
                "recommendation": "string",
                "confidence": "0-1",
            }],
        },
        "topics": topics_payload,
    }

    result = run_llm_command(
        payload=payload,
        command=llm_command,
        timeout=llm_timeout,
    )

    if result.status != "ok":
        logger.warning("LLM QA verification failed: %s", result.parsed.get("reason", "unknown"))
        return []

    verification = result.parsed.get("verification", [])
    if not isinstance(verification, list):
        return []
    return [item for item in verification if isinstance(item, dict)]


# ---------------------------------------------------------------------------
# LLM-driven report section generators
# ---------------------------------------------------------------------------

def generate_executive_summary_via_llm(
    ranked: list[dict],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    llm_command: str,
    llm_timeout: float = LLM_REPORT_SECTION_TIMEOUT_SECONDS,
    consensus_summary: dict | None = None,
    strategy_cards: list[dict] | None = None,
    research_sources: list[dict[str, str]] | None = None,
    agent_decisions: dict[str, list[dict]] | None = None,
    asis_analysis: dict | None = None,
    tobe_direction: dict | None = None,
    feasibility_evidence: dict | None = None,
) -> dict:
    """Generate Executive Summary via LLM."""
    topics_payload = _build_topic_payload(
        ranked, states, scores=scores, agent_decisions=agent_decisions,
        max_evidence_snippets=0, include_agent_scores=True, include_agent_decisions=True,
    )

    consensus = consensus_summary or {}
    cards_summary = []
    for card in (strategy_cards or []):
        cards_summary.append({
            "topic_id": card.get("topic_id", ""),
            "topic_name": card.get("topic_name", ""),
            "innovation_ideas": card.get("innovation_ideas", [])[:3],
            "risk_mitigation": card.get("risk_mitigation", ""),
            "expected_impact": card.get("expected_impact", ""),
        })

    payload = {
        "version": "llm-executive-summary-v1",
        "aggregate_stats": _build_aggregate_stats(states, scores=scores, research_sources=research_sources),
        "system_prompt": (
            "You are a PhD-level R&D strategist and Google Staff Engineer-level technical advisor. "
            "Write a comprehensive Executive Summary for an R&D strategy report. "
            "Requirements:\n"
            "- Start with a 2-3 sentence thesis statement summarizing the overall strategic direction\n"
            "- For each selected topic, explain WHY it was selected — cite evidence count, agent consensus patterns, paper validation\n"
            "- Quantify expected impact using feature scores (impact/feasibility/novelty) and evidence counts\n"
            "- Derive 2-3 overarching strategic themes that connect the selected topics\n"
            "- Identify top 2-3 risks with mitigation paths, extracted from deliberation concerns\n"
            "- 800-1200 words, in Korean\n"
            "- Every claim must have quantitative backing\n\n"
            "Return JSON: {\"executive_summary\": {\"thesis\": \"...\", \"topic_rationales\": "
            "[{\"topic_id\": \"...\", \"rationale\": \"...\"}], \"strategic_themes\": "
            "[\"...\"], \"risk_assessment\": \"...\", \"full_text\": \"...\"}}"
        ),
        "output_contract": {
            "executive_summary": {
                "thesis": "string",
                "topic_rationales": [{"topic_id": "string", "rationale": "string"}],
                "strategic_themes": ["string"],
                "risk_assessment": "string",
                "full_text": "string (800-1200 words, Korean)",
            },
        },
        "topics": topics_payload,
        "consensus": {
            "final_ids": consensus.get("final_consensus_ids", []),
            "rationale": consensus.get("final_rationale", ""),
            "concerns": consensus.get("concerns", []),
        },
        "strategy_cards_summary": cards_summary,
        "research_sources": (research_sources or [])[:15],
        "prior_sections": {
            "asis_summary": (asis_analysis or {}).get("full_text", "")[:500],
            "tobe_summary": (tobe_direction or {}).get("full_text", "")[:500],
            "feasibility_summary": (feasibility_evidence or {}).get("full_text", "")[:500],
        },
    }

    result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
    if result.status != "ok":
        logger.warning("LLM executive summary generation failed: %s", result.parsed.get("reason", "unknown"))
        return {}
    return result.parsed.get("executive_summary", {})


def generate_asis_analysis_via_llm(
    ranked: list[dict],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    llm_command: str,
    llm_timeout: float = LLM_REPORT_SECTION_TIMEOUT_SECONDS,
) -> dict:
    """Generate As-Is (current technology status) analysis via LLM."""
    topics_payload = _build_topic_payload(
        states, states, scores=scores,
        include_code_doc=True, include_project_hits=True,
        include_agent_scores=True, include_evidence_files=True,
    )

    # Aggregate stats
    total_evidence = sum(len(s.evidence) for s in states.values())
    total_code_hits = sum(s.code_hits for s in states.values())
    all_projects: dict[str, int] = {}
    for s in states.values():
        for proj, count in s.project_hits.items():
            all_projects[proj] = all_projects.get(proj, 0) + count

    payload = {
        "version": "llm-asis-analysis-v1",
        "system_prompt": (
            "You are a PhD-level R&D strategist and Google Staff Engineer-level technical advisor. "
            "Write a comprehensive As-Is technology analysis. "
            "Requirements:\n"
            "- Technology inventory: diagnose technology patterns per service scope (B2B, B2C, AI, Telecom), "
            "citing project names and hit counts\n"
            "- Strengths: areas where code_hits AND project_count are high = mature implementation. "
            "Cite evidence snippets\n"
            "- Weaknesses/tech debt: where doc_hits >> code_hits (discussed but not implemented), "
            "topics with high features.risk_penalty score (>6.0), areas lacking evidence\n"
            "- Maturity matrix: rate each topic as Conceptual → Prototype → Integrated → Production\n"
            "- Every claim MUST have quantitative data\n"
            "- 1000-1500 words, in Korean\n\n"
            "Return JSON: {\"asis_analysis\": {\"technology_inventory\": "
            "[{\"scope\": \"...\", \"patterns\": \"...\", \"projects\": [\"...\"]}], "
            "\"strengths\": [{\"area\": \"...\", \"evidence\": \"...\"}], "
            "\"weaknesses\": [{\"area\": \"...\", \"evidence\": \"...\"}], "
            "\"maturity_matrix\": [{\"topic_id\": \"...\", \"topic_name\": \"...\", \"level\": \"...\", \"rationale\": \"...\"}], "
            "\"full_text\": \"...\"}}"
        ),
        "output_contract": {
            "asis_analysis": {
                "technology_inventory": [{"scope": "string", "patterns": "string", "projects": ["string"]}],
                "strengths": [{"area": "string", "evidence": "string"}],
                "weaknesses": [{"area": "string", "evidence": "string"}],
                "maturity_matrix": [{"topic_id": "string", "topic_name": "string", "level": "string", "rationale": "string"}],
                "full_text": "string (1000-1500 words, Korean)",
            },
        },
        "all_topics": topics_payload,
        "ranked_topics": [
            {"topic_id": item["topic_id"], "topic_name": item["topic_name"],
             "total_score": item.get("total_score", 0), "features": item.get("features", {})}
            for item in ranked
        ],
        "aggregate_stats": {
            "total_topics": len(states),
            "total_evidence": total_evidence,
            "total_code_hits": total_code_hits,
            "project_topic_coverage": {
                proj: count for proj, count in sorted(all_projects.items(), key=lambda x: x[1], reverse=True)[:15]
            },
        },
    }

    result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
    if result.status != "ok":
        logger.warning("LLM As-Is analysis generation failed: %s", result.parsed.get("reason", "unknown"))
        return {}
    return result.parsed.get("asis_analysis", {})


def generate_tobe_direction_via_llm(
    ranked: list[dict],
    states: dict[str, TopicState],
    llm_command: str,
    llm_timeout: float = LLM_REPORT_SECTION_TIMEOUT_SECONDS,
    asis_analysis: dict | None = None,
    strategy_cards: list[dict] | None = None,
    research_sources: list[dict[str, str]] | None = None,
) -> dict:
    """Generate To-Be technology direction via LLM."""
    topics_payload = _build_topic_payload(
        ranked, states,
        max_evidence_snippets=4, include_project_hits=True, include_evidence_files=True,
    )

    cards_payload = []
    for card in (strategy_cards or []):
        cards_payload.append({
            "topic_id": card.get("topic_id", ""),
            "topic_name": card.get("topic_name", ""),
            "innovation_ideas": card.get("innovation_ideas", []),
            "action_plan": card.get("action_plan", []),
        })

    payload = {
        "version": "llm-tobe-direction-v1",
        "system_prompt": (
            "You are a PhD-level R&D strategist and Google Staff Engineer-level technical advisor. "
            "Write a comprehensive To-Be technology direction. "
            "Requirements:\n"
            "- As-Is → To-Be transition: describe specific architecture/technology transformations. "
            "NOT vague 'improve performance' but specific like 'transition from HTTP polling to "
            "WebSocket bidirectional streaming, P99 latency ~800ms → <200ms expected'\n"
            "- Architecture changes: new components, changed interfaces, deprecated patterns. "
            "Reference evidence file/project names\n"
            "- Expected performance/quality improvements: quantify based on feature scores (impact, feasibility) "
            "and research_sources summaries. Only cite benchmarks that appear in the provided data\n"
            "- Technology dependency chain: infer precedence between topics from shared projects "
            "(project_hits overlap) and feature complementarity\n"
            "- 1200-1800 words, in Korean\n"
            "- Every claim must have quantitative backing\n\n"
            "Return JSON: {\"tobe_direction\": {\"per_topic\": "
            "[{\"topic_id\": \"...\", \"topic_name\": \"...\", \"current_state\": \"...\", "
            "\"target_state\": \"...\", \"key_changes\": [\"...\"], \"expected_improvement\": \"...\"}], "
            "\"cross_cutting_changes\": \"...\", \"full_text\": \"...\"}}"
        ),
        "output_contract": {
            "tobe_direction": {
                "per_topic": [{"topic_id": "string", "topic_name": "string", "current_state": "string",
                               "target_state": "string", "key_changes": ["string"], "expected_improvement": "string"}],
                "cross_cutting_changes": "string",
                "full_text": "string (1200-1800 words, Korean)",
            },
        },
        "selected_topics": topics_payload,
        "asis_analysis": asis_analysis or {},
        "strategy_cards": cards_payload,
        "research_sources": [
            {"title": s.get("title", ""), "url": s.get("url", ""), "summary": s.get("summary", ""),
             "id": s.get("id", ""), "provider": s.get("provider", ""), "published": s.get("published", "")}
            for s in (research_sources or [])[:15]
        ],
    }

    result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
    if result.status != "ok":
        logger.warning("LLM To-Be direction generation failed: %s", result.parsed.get("reason", "unknown"))
        return {}
    return result.parsed.get("tobe_direction", {})


def generate_feasibility_evidence_via_llm(
    ranked: list[dict],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    llm_command: str,
    llm_timeout: float = LLM_REPORT_SECTION_TIMEOUT_SECONDS,
    agent_definitions: dict[str, dict] | None = None,
    consensus_summary: dict | None = None,
    strategy_cards: list[dict] | None = None,
    research_sources: list[dict[str, str]] | None = None,
    pipeline_decisions: list | None = None,
) -> dict:
    """Generate feasibility evidence via LLM."""
    topics_payload = _build_topic_payload(
        ranked, states, scores=scores,
        include_code_doc=True, include_project_hits=True,
        include_agent_scores=True, include_evidence_files=True,
    )

    agent_roles = []
    for agent_name, definition in (agent_definitions or {}).items():
        agent_roles.append({
            "agent": agent_name,
            "objective": definition.get("objective", ""),
            "score_example": scores.get(ranked[0]["topic_id"], {}).get(_agent_score_key(agent_name), 0) if ranked else 0,
        })

    decisions_payload = []
    for d in (pipeline_decisions or []):
        record = d.to_dict() if hasattr(d, "to_dict") else dict(d)
        decisions_payload.append({
            "topic_id": record.get("topic_id", ""),
            "risk": record.get("risk", ""),
            "confidence": record.get("confidence", 0),
            "rationale": record.get("rationale", ""),
        })

    payload = {
        "version": "llm-feasibility-evidence-v1",
        "aggregate_stats": _build_aggregate_stats(states, scores=scores, research_sources=research_sources),
        "system_prompt": (
            "You are a PhD-level R&D strategist and Google Staff Engineer-level technical advisor. "
            "Write a comprehensive feasibility evidence analysis. "
            "Requirements:\n"
            "- Existing asset evidence: cite project name, code hit count, evidence file path. "
            "Example: 'OraAIServer has 12 code_hits for embedding → RAG pipeline infrastructure ~35% already available'\n"
            "- Team capability evidence: map agent scores to real team capabilities. "
            "Example: 'Developer 8.2 + Researcher 7.8 = implementation power + academic foundation'\n"
            "- Market/industry evidence: ground in business_hits + novelty_hits for market relevance\n"
            "- Academic evidence: cite papers using the 'id' and 'title' fields from research_sources. "
            "Example: 'MetaRAG (arXiv:2509.09360) demonstrated 23% reduction in RAG hallucination'. "
            "ONLY cite papers that appear in the research_sources list — do NOT invent paper IDs\n"
            "- Per-topic feasibility verdict: HIGH(>70%) / MEDIUM(40-70%) / LOW(<40%)\n"
            "- 1000-1500 words, in Korean\n"
            "- Every claim must have quantitative backing\n\n"
            "Return JSON: {\"feasibility_evidence\": {\"per_topic\": "
            "[{\"topic_id\": \"...\", \"topic_name\": \"...\", \"asset_evidence\": \"...\", "
            "\"team_capability\": \"...\", \"market_evidence\": \"...\", \"academic_evidence\": \"...\", "
            "\"verdict\": \"HIGH|MEDIUM|LOW\", \"confidence_pct\": 75}], "
            "\"overall_portfolio_feasibility\": \"...\", \"full_text\": \"...\"}}"
        ),
        "output_contract": {
            "feasibility_evidence": {
                "per_topic": [{"topic_id": "string", "topic_name": "string", "asset_evidence": "string",
                               "team_capability": "string", "market_evidence": "string",
                               "academic_evidence": "string", "verdict": "HIGH|MEDIUM|LOW", "confidence_pct": "int"}],
                "overall_portfolio_feasibility": "string",
                "full_text": "string (1000-1500 words, Korean)",
            },
        },
        "selected_topics": topics_payload,
        "agent_roles": agent_roles,
        "consensus_signals": {
            "concerns": (consensus_summary or {}).get("concerns", []),
            "final_rationale": (consensus_summary or {}).get("final_rationale", ""),
        },
        "research_sources": [
            {"title": s.get("title", ""), "url": s.get("url", ""),
             "summary": s.get("summary", ""), "authors": s.get("authors", ""),
             "id": s.get("id", ""), "provider": s.get("provider", ""),
             "published": s.get("published", "")}
            for s in (research_sources or [])[:15]
        ],
        "pipeline_decisions": decisions_payload[:20],
    }

    result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
    if result.status != "ok":
        logger.warning("LLM feasibility evidence generation failed: %s", result.parsed.get("reason", "unknown"))
        return {}
    return result.parsed.get("feasibility_evidence", {})


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

def _agent_score_key(agent: str) -> str:
    return agent.lower().replace(" ", "_")


def _clamp_score(value: float, lo: float = 0.0, hi: float = 10.0) -> float:
    return max(lo, min(hi, round(value, 2)))


# ---------------------------------------------------------------------------
# Scoring / ranking builders
# ---------------------------------------------------------------------------

def build_global_scores(
    scores: dict[str, dict[str, float]],
    agent_weights: dict[str, float] | None = None,
) -> list[tuple[str, float]]:
    weights = agent_weights or AGENT_FINAL_WEIGHTS
    agents = set(weights.keys())
    topic_votes = _rank_from_scores(scores, agents)
    totals: list[tuple[str, float]] = []
    for topic_id in scores:
        weighted_sum = 0.0
        for agent_id, agent_weight in weights.items():
            weighted_sum += agent_weight * scores[topic_id].get(_agent_score_key(agent_id), 0.0)
        weighted_sum += 0.02 * topic_votes[topic_id]
        total = round(weighted_sum, 2)
        totals.append((topic_id, total))
    return sorted(totals, key=lambda item: item[1], reverse=True)


def _rank_from_scores(
    scores: dict[str, dict[str, float]],
    agents: set[str] | None = None,
) -> dict[str, int]:
    agents = agents or set(AGENT_FINAL_WEIGHTS.keys())
    by_agent = {
        agent: sorted(
            scores.items(),
            key=lambda i: i[1].get(_agent_score_key(agent), 0.0),
            reverse=True,
        )
        for agent in agents
    }
    rank_map = {topic_id: 0 for topic_id in scores}
    for agent_scores in by_agent.values():
        for rank, (topic_id, _) in enumerate(agent_scores, start=1):
            rank_map[topic_id] += max(0, 20 - rank)
    return rank_map


def build_final_score(
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    agent_weights: dict[str, float] | None = None,
    agent_ids: list[str] | None = None,
) -> list[dict]:
    weights = agent_weights or AGENT_FINAL_WEIGHTS
    agents = set(weights.keys())
    topic_votes = _rank_from_scores(scores, agents)
    all_agent_ids = agent_ids or sorted(weights.keys())
    output: list[dict] = []

    for topic_id, state in states.items():
        feature = state.compute_features()
        total = 0.0
        for agent_id, agent_weight in weights.items():
            total += agent_weight * scores[topic_id].get(_agent_score_key(agent_id), 0.0)
        total = round(total + 0.02 * topic_votes[topic_id], 2)
        row: dict[str, object] = {
            "topic_id": topic_id,
            "topic_name": state.topic_name,
            "total_score": total,
            "features": feature,
            "project_count": state.project_count,
            "evidence_count": len(state.evidence),
            "evidence": [e.snippet for e in state.evidence[:4]],
        }
        for agent_id in all_agent_ids:
            row[_agent_score_key(agent_id)] = scores[topic_id].get(_agent_score_key(agent_id), 0.0)
        output.append(row)
    output.sort(key=lambda x: x["total_score"], reverse=True)
    return output


def build_agent_rankings(
    scores: dict[str, dict[str, float]],
    top_k: int,
    agent_filter: set[str] | None = None,
) -> dict[str, list[str]]:
    agents = agent_filter if agent_filter else set(AGENT_FINAL_WEIGHTS.keys())
    rankings: dict[str, list[str]] = {}
    for agent in agents:
        key = _agent_score_key(agent)
        ranked_agent = sorted(scores.items(), key=lambda item: item[1].get(key, 0.0), reverse=True)
        rankings[agent] = [topic_id for topic_id, _ in ranked_agent[:top_k]]
    return rankings


def build_consensus_via_llm(
    agent_rankings: dict[str, list[str]],
    ranked: list[dict],
    llm_command: str | None = None,
    llm_timeout: float = 15.0,
    top_k: int = 6,
) -> list[str]:
    """Build consensus ranking via LLM. Falls back to simple aggregation on failure."""
    payload = {
        "version": "llm-consensus-rank-v1",
        "system_prompt": (
            "You are a research committee secretary. "
            "Given each agent's ranked topic preferences, produce a single consensus ranking "
            "that best represents the committee's priorities. "
            "Consider topic scores, diversity of support across agents, and strategic balance. "
            "Return JSON: {\"consensus\": [\"topic_id_1\", \"topic_id_2\", ...]}"
        ),
        "agent_rankings": agent_rankings,
        "topics": [
            {"topic_id": item["topic_id"], "topic_name": item["topic_name"],
             "total_score": item.get("total_score", 0), "features": item.get("features", {})}
            for item in ranked[:top_k * 2]
        ],
        "target_size": top_k,
    }

    if llm_command:
        result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
        if result.status == "ok":
            ids = result.parsed.get("consensus", [])
            if isinstance(ids, list) and len(ids) >= 1:
                return [str(tid) for tid in ids if isinstance(tid, str)][:top_k]

    # Simple aggregation fallback (no hardcoded weights — just count appearances)
    topic_score: dict[str, float] = {}
    for agent, topics in agent_rankings.items():
        for rank, topic_id in enumerate(topics[:top_k], start=1):
            topic_score[topic_id] = topic_score.get(topic_id, 0.0) + max(0, top_k + 1 - rank)
    return [tid for tid, _ in sorted(topic_score.items(), key=lambda x: x[1], reverse=True)][:top_k]


def build_phase_plan_via_llm(
    ranked: list[dict],
    top_k: int,
    llm_command: str | None = None,
    llm_timeout: float = 15.0,
) -> list[dict]:
    """Build phase plan via LLM. Falls back to score-based distribution on failure."""
    payload = {
        "version": "llm-phase-plan-v1",
        "system_prompt": (
            "You are a strategic R&D planner. Given ranked research topics with their features "
            "(impact, feasibility, novelty, risk_penalty, research_signal), assign each topic "
            "to one of three execution phases:\n"
            "- Phase 1 (Month 1-2): Quick wins with high feasibility and immediate impact\n"
            "- Phase 2 (Month 3-4): Pilot projects needing integration or moderate effort\n"
            "- Phase 3 (Month 5-8): Long-term research tracks with high novelty but more risk\n\n"
            "For each topic, also provide a one-line goal. "
            "Return JSON: {\"phases\": [{\"phase\": \"Month 1-2\", \"topics\": "
            "[{\"rank\": 1, \"topic_id\": \"...\", \"topic\": \"...\", \"score\": 7.5, \"goal\": \"...\"}]}, ...]}"
        ),
        "topics": [
            {
                "rank": idx,
                "topic_id": item["topic_id"],
                "topic_name": item["topic_name"],
                "total_score": item.get("total_score", 0),
                "features": item.get("features", {}),
            }
            for idx, item in enumerate(ranked[:top_k], start=1)
        ],
    }

    if llm_command:
        result = run_llm_command(payload=payload, command=llm_command, timeout=llm_timeout)
        if result.status == "ok":
            phases = result.parsed.get("phases", [])
            if isinstance(phases, list) and len(phases) >= 1:
                return [p for p in phases if isinstance(p, dict) and p.get("topics")]

    # Fallback: distribute evenly by rank (no hardcoded thresholds)
    phase_labels = ["Month 1-2", "Month 3-4", "Month 5-8"]
    items = ranked[:top_k]
    n = len(items)
    chunk = max(1, (n + 2) // 3)
    phases: list[dict] = []
    for i, label in enumerate(phase_labels):
        group = items[i * chunk:(i + 1) * chunk]
        if not group:
            continue
        phases.append({
            "phase": label,
            "topics": [
                {
                    "rank": i * chunk + j + 1,
                    "topic_id": item["topic_id"],
                    "topic": item["topic_name"],
                    "score": item.get("total_score", 0),
                    "goal": "Prioritized by overall score ranking",
                }
                for j, item in enumerate(group)
            ],
        })
    return phases


# ---------------------------------------------------------------------------
# Strategy card sub-builders
# ---------------------------------------------------------------------------

def _top_projects_summary(state: TopicState, limit: int = 5) -> str:
    if not state.project_hits:
        return "프로젝트 근거 미확인"
    items = sorted(state.project_hits.items(), key=lambda item: item[1], reverse=True)
    joined = ", ".join(f"{name}({count}회)" for name, count in items[:limit])
    rest = len(items) - min(len(items), limit)
    if rest > 0:
        joined = f"{joined}, +{rest}개"
    return joined




def build_synergy_graph(states: dict[str, TopicState], ranked: list[dict]) -> list[str]:
    selected = {item["topic_id"] for item in ranked[:6]}
    items = sorted(selected)
    lines: list[str] = []
    for i, t1 in enumerate(items):
        for t2 in items[i + 1:]:
            overlap = len(set(states[t1].project_hits.keys()) & set(states[t2].project_hits.keys()))
            if overlap >= 2:
                lines.append(
                    f"- {states[t1].topic_name} ↔ {states[t2].topic_name}: "
                    f"공통 파일군 {overlap}개 프로젝트에서 확인"
                )
    if not lines:
        lines.append("- 현재 분석 스냅샷 기준, 강한 증거 교집합은 부족해 보이나 정책/UX/모니터링 레이어로 연계 가능성 큼")
    return lines


def _format_report_title(version_tag: str, report_focus: str) -> str:
    focus_text = report_focus.strip()
    if focus_text:
        return f"Ora 프로젝트 R&D 연구 주제 선정 보고서 ({version_tag} — {focus_text})"
    return f"Ora 프로젝트 R&D 연구 주제 선정 보고서 ({version_tag})"


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def as_markdown(
    workspace: Path,
    top_topics: list[dict],
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    ranked: list[dict],
    agent_rankings: dict[str, list[str]],
    phases: list[dict],
    synergy_lines: list[str],
    queries: list[dict[str, str]],
    report_focus: str,
    version_tag: str,
    agent_definitions: dict[str, dict] | None = None,
    research_sources: list[dict[str, str]] | None = None,
    agent_decisions: dict[str, list[dict]] | None = None,
    discussion: list[dict] | None = None,
    debate_rounds: int = DEBATE_ROUNDS_DEFAULT,
    consensus_summary: dict | None = None,
    orchestration_profile: str = ORCHESTRATION_PROFILE_DEFAULT,
    orchestration_stages: list[str] | None = None,
    pipeline_decisions: list[dict] | list[OrchestrationDecision] | None = None,
    pipeline_stage_log: list[dict] | None = None,
    service_scope: list[str] | None = None,
    feature_scope: list[str] | None = None,
    hierarchical_analysis: dict | None = None,
    strategy_cards_prebuilt: list[dict] | None = None,
    qa_verification: list[dict] | None = None,
    # --- new report sections (LLM-generated) ---
    executive_summary: dict | None = None,
    asis_analysis: dict | None = None,
    tobe_direction: dict | None = None,
    feasibility_evidence: dict | None = None,
) -> str:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    defs = agent_definitions or {}
    is_hierarchical = hierarchical_analysis is not None
    if is_hierarchical:
        agent_order = sorted(FLAT_MODE_AGENTS) + sorted(
            name for name in defs if name not in FLAT_MODE_AGENTS
        )
    else:
        agent_order = [name for name in AGENT_FINAL_WEIGHTS]
    agent_title_map = {
        "CEO": "대표(CEO)",
        "Planner": "기획자(Planner)",
        "Developer": "개발자(Developer)",
        "Researcher": "연구자(Researcher)",
        "PM": "PM",
        "Ops": "운영(Ops)",
        "QA": "QA",
        "SecuritySpecialist": "보안전문가(Security)",
        "Linguist": "언어학자(Linguist)",
        "MarketAnalyst": "시장분석가(Market)",
        "FinanceAnalyst": "재무분석가(Finance)",
        "UXVoiceDesigner": "음성UX설계(VoiceUX)",
        "DataScientist": "데이터사이언티스트(DS)",
        "DevOpsSRE": "데브옵스(DevOps/SRE)",
        "QALead": "QA팀장(QALead)",
    }
    orchestration_stages = _normalize_stages(orchestration_stages, fallback=ORCHESTRATION_STAGES_DEFAULT)
    pipeline_decisions = pipeline_decisions or []
    pipeline_stage_log = pipeline_stage_log or []
    service_scope = service_scope or []
    feature_scope = feature_scope or []
    topic_name_by_id = {item["topic_id"]: item["topic_name"] for item in ranked}
    sources = research_sources or []
    final_consensus_ids = (
        consensus_summary.get("final_consensus_ids", [])
        if consensus_summary
        else []
    )
    consensus_lines = [f"- {topic_name_by_id.get(topic_id, topic_id)}" for topic_id in final_consensus_ids]
    query_lines = [f"- {item['topic_name']}: `{item['web_query']}`" for item in queries]
    strategy_cards = strategy_cards_prebuilt or _build_minimal_cards(top_topics, states, agent_decisions, sources)
    source_lines = [
        "- "
        + (f"{item.get('topic', '')}: " if item.get("topic", "") else "")
        + f"[{item.get('title', 'reference')}]({item.get('url', '')})"
        + (f" ({item.get('status', '')})" if item.get("status") else "")
        for item in sources[:20]
    ]

    table_headers = ["순위", "주제"]
    table_headers.extend(agent_order)
    table_headers.extend(["통합점수", "피처 점수(영향/실행성/혁신성)"])
    table_rows = [
        "| " + " | ".join(table_headers) + " |",
        "|" + "|".join(["---"] * len(table_headers)) + "|",
    ]
    for idx, item in enumerate(top_topics, start=1):
        feature = item["features"]
        row_values = [str(idx), item["topic_name"]]
        for agent in agent_order:
            row_values.append(str(item.get(_agent_score_key(agent), 0.0)))
        row_values.append(str(item["total_score"]))
        row_values.append(f"{feature['impact']} / {feature['feasibility']} / {feature['novelty']}")
        table_rows.append("| " + " | ".join(row_values) + " |")

    phases_md = []
    for phase in phases:
        bullets = [f"- {t['topic']} ({t['goal']}, 점수 {t['score']})" for t in phase["topics"]]
        if not bullets:
            continue
        phases_md.append(f"### {phase['phase']}\n" + "\n".join(bullets))

    evidence_md = []
    for item in top_topics:
        evidence_md.append(f"### {item['topic_name']}")
        if not item["evidence"]:
            evidence_md.append("- 증거 없음")
            continue
        for line in item["evidence"]:
            evidence_md.append(f"- {line}")

    sections: list[str] = []
    sections.append(f"# {_format_report_title(version_tag, report_focus)}")
    sections.append(f"> **작성일**: {now}")
    sections.append("**참여자**: " + ", ".join(agent_title_map.get(agent, agent) for agent in agent_order))
    sections.append(f"**범위**: `{workspace}`")
    sections.append(f"**오케스트레이션**: profile=`{orchestration_profile}` stages=`{','.join(orchestration_stages)}`")
    if service_scope:
        sections.append(f"**서비스 스코프**: {', '.join(service_scope)}")
    if feature_scope:
        sections.append(f"**기능 스코프**: {', '.join(feature_scope)}")
    sections.append("---")

    # --- Section 1: Executive Summary (LLM-generated) ---
    sections.append("## 1. Executive Summary")
    exec_summary = executive_summary or {}
    exec_full = exec_summary.get("full_text", "")
    if exec_full:
        sections.append(exec_full)
    else:
        # Structured fallback from sub-fields
        thesis = exec_summary.get("thesis", "")
        if thesis:
            sections.append(thesis)
        rationales = exec_summary.get("topic_rationales", [])
        if rationales:
            sections.append("")
            for r in rationales:
                if isinstance(r, dict):
                    tid = r.get("topic_id", "")
                    sections.append(f"- **{topic_name_by_id.get(tid, tid)}**: {r.get('rationale', '')}")
        themes = exec_summary.get("strategic_themes", [])
        if themes:
            sections.append("")
            sections.append("**전략 테마:**")
            for theme in themes:
                sections.append(f"- {theme}")
        risk_text = exec_summary.get("risk_assessment", "")
        if risk_text:
            sections.append("")
            sections.append(f"**리스크 평가:** {risk_text}")
        if not thesis and not rationales:
            sections.append("- Executive Summary가 생성되지 않았습니다.")
    sections.append("")

    # --- Section 2: Final R&D topics (existing) ---
    sections.append(f"## 2. 최종 확정 R&D 주제 (TOP {len(top_topics)})")
    sections.extend(table_rows)
    sections.append("")

    sections.append("## 2.1 협력 에이전트 역할·판단 구조")
    sections.append("- 각 에이전트는 아래 기준으로 1차 판단(지원/이의/재검토/중립)을 수행합니다.")
    ordered_defs: list[tuple[str, dict]] = []
    for agent_name in agent_order:
        if agent_name in defs:
            ordered_defs.append((agent_name, defs.get(agent_name, {})))
    if not ordered_defs:
        ordered_defs = list(defs.items())
    for agent_name, profile in ordered_defs:
        weight_lines = [f"{k}:{v:.2f}" for k, v in (profile.get("weights") or {}).items()]
        sections.append(f"### {agent_name}")
        sections.append(f"- 목표: {profile.get('objective', '')}")
        sections.append(f"- 가중치: {' / '.join(weight_lines)}")
        sections.append("- 판단 포인트:")
        for focus in profile.get("decision_focus", []):
            sections.append(f"  - {focus}")
        sections.append("")

    # --- Section 3: As-Is Analysis (LLM-generated) ---
    sections.append("## 3. 현재 기술 수준 분석 (As-Is)")
    asis = asis_analysis or {}
    asis_full = asis.get("full_text", "")
    if asis_full:
        sections.append(asis_full)
    else:
        tech_inv = asis.get("technology_inventory", [])
        if tech_inv:
            sections.append("### 기술 자산 현황")
            for inv in tech_inv:
                if isinstance(inv, dict):
                    sections.append(f"- **{inv.get('scope', '')}**: {inv.get('patterns', '')}")
                    projs = inv.get("projects", [])
                    if projs:
                        sections.append(f"  - 프로젝트: {', '.join(projs)}")
        strengths = asis.get("strengths", [])
        if strengths:
            sections.append("### 강점")
            for s in strengths:
                if isinstance(s, dict):
                    sections.append(f"- **{s.get('area', '')}**: {s.get('evidence', '')}")
        weaknesses = asis.get("weaknesses", [])
        if weaknesses:
            sections.append("### 약점/기술 부채")
            for w in weaknesses:
                if isinstance(w, dict):
                    sections.append(f"- **{w.get('area', '')}**: {w.get('evidence', '')}")
        maturity = asis.get("maturity_matrix", [])
        if maturity:
            sections.append("### 성숙도 매트릭스")
            for m in maturity:
                if isinstance(m, dict):
                    sections.append(f"- {m.get('topic_name', m.get('topic_id', ''))}: **{m.get('level', '-')}** — {m.get('rationale', '')}")
        if not tech_inv and not strengths:
            sections.append("- As-Is 분석이 생성되지 않았습니다.")
    sections.append("")

    # --- Section 4: To-Be Direction (LLM-generated) ---
    sections.append("## 4. 기술 고도화 방향 (To-Be)")
    tobe = tobe_direction or {}
    tobe_full = tobe.get("full_text", "")
    if tobe_full:
        sections.append(tobe_full)
    else:
        per_topic_tobe = tobe.get("per_topic", [])
        if per_topic_tobe:
            for pt in per_topic_tobe:
                if not isinstance(pt, dict):
                    continue
                tid = pt.get("topic_id", "")
                sections.append(f"### {topic_name_by_id.get(tid, pt.get('topic_name', tid))}")
                if pt.get("current_state"):
                    sections.append(f"- 현재: {pt['current_state']}")
                if pt.get("target_state"):
                    sections.append(f"- 목표: {pt['target_state']}")
                for kc in pt.get("key_changes", []):
                    sections.append(f"  - {kc}")
                if pt.get("expected_improvement"):
                    sections.append(f"- 기대 개선: {pt['expected_improvement']}")
            cross = tobe.get("cross_cutting_changes", "")
            if cross:
                sections.append("")
                sections.append(f"### 공통 아키텍처 변화\n{cross}")
        else:
            sections.append("- To-Be 방향이 생성되지 않았습니다.")
    sections.append("")

    # --- Section 5: Strategy cards + QA (existing, renumbered) ---
    sections.append("## 5. R&D 전략별 상세 실행안 + QA 검증")
    for card in strategy_cards:
        sections.append(f"### 전략 {card.get('rank', '?')}: {card.get('topic_name', card.get('topic_id', ''))}")
        sections.append(f"- 통합 점수: {card.get('score', 0)} / 토픽 근거 샘플: {card.get('evidence_count', 0)}건")
        fp = card.get("feature_profile", {})
        if fp:
            sections.append(
                f"- 특성: 영향 {fp.get('impact', '-')} / 실행성 {fp.get('feasibility', '-')} / "
                f"혁신성 {fp.get('novelty', '-')} / 리스크 {fp.get('risk_penalty', '-')} / 연구신호 {fp.get('research_signal', '-')}"
            )
        sections.append("- 프로젝트/증거 분포: " + card.get("project_snapshot", ""))

        # Innovation ideas (LLM-generated)
        ideas = card.get("innovation_ideas", [])
        if ideas:
            sections.append("#### 혁신 아이디어")
            for idea in ideas:
                if isinstance(idea, dict):
                    sections.append(f"- **{idea.get('idea', '')}**")
                    if idea.get("differentiator"):
                        sections.append(f"  - 차별점: {idea['differentiator']}")
                    if idea.get("expected_impact"):
                        sections.append(f"  - 기대 효과: {idea['expected_impact']}")
                elif isinstance(idea, str):
                    sections.append(f"- {idea}")

        # Competitive edge
        edge = card.get("competitive_edge", "")
        if edge:
            sections.append("#### 경쟁 우위")
            sections.append(f"- {edge}")

        # Agent decisions
        sections.append("#### 협력 에이전트 판단")
        for dec in card.get("agent_decisions", []):
            status = dec.get("decision", "review")
            status_label = {"support": "지원", "challenge": "이의/보류", "review": "재검토", "hold": "중립"}.get(status, "재검토")
            sections.append(f"- {dec.get('agent', '?')} ({status_label}, 점수 {dec.get('score', 0):.2f}): {dec.get('reason', '')}")
            focus = ", ".join(dec.get("focus", []))
            if focus:
                sections.append(f"  - 판단 포인트: {focus}")

        # Cause analysis
        causes = card.get("cause_analysis", [])
        if causes:
            sections.append("#### 원인 진단")
            for cause in causes:
                sections.append(f"- {cause}")

        # Evidence snapshots
        sections.append("#### 근거 스냅샷")
        snapshots = card.get("evidence_snapshots", [])
        if snapshots:
            for ev in snapshots:
                sections.append(f"- `{ev.get('file', '')}:{ev.get('line', '')}` {ev.get('snippet', '')}")
        else:
            sections.append("- 상위 근거가 충분히 누적되지 않음")

        # Action plan
        plan = card.get("action_plan", [])
        if plan:
            sections.append("#### 액션 플랜")
            for step in plan:
                if isinstance(step, dict):
                    sections.append(f"- **{step.get('phase', '')}**")
                    for t in step.get("tasks", []):
                        sections.append(f"  - {t}")

        # Success metrics
        metrics = card.get("success_metrics", [])
        if metrics:
            sections.append("#### 성공 지표(Go/No-Go 기준)")
            for m in metrics:
                sections.append(f"- {m}")

        # Expected impact & risk mitigation (LLM-generated)
        expected = card.get("expected_impact", "")
        if expected:
            sections.append(f"#### 기대 효과\n- {expected}")
        risk_mit = card.get("risk_mitigation", "")
        if risk_mit:
            sections.append(f"#### 리스크 완화\n- {risk_mit}")

        # Papers
        papers = card.get("papers", [])
        if papers:
            sections.append("#### 관련 논문/자료(근거)")
            for paper in papers:
                status = paper.get("status", "")
                status_text = f" [{status}]" if status else ""
                arxiv_id = paper.get("id", "")
                if arxiv_id:
                    sections.append(f"- [{paper.get('title', 'reference')}]({paper.get('url', '')}){status_text} (`{arxiv_id}`)")
                else:
                    sections.append(f"- [{paper.get('title', 'reference')}]({paper.get('url', '')}){status_text}")
    sections.append("")

    # QA verification sub-section under strategy cards
    if qa_verification:
        sections.append("### QA 검증 결과")
        for qa_item in qa_verification:
            if not isinstance(qa_item, dict):
                continue
            topic_id = qa_item.get("topic_id", "")
            passed = qa_item.get("passed", False)
            quality = qa_item.get("evidence_quality", "-")
            qa_conf = qa_item.get("confidence", "-")
            status_icon = "PASS" if passed else "FAIL"
            sections.append(f"#### {topic_name_by_id.get(topic_id, topic_id)} [{status_icon}]")
            sections.append(f"- 증거 품질: {quality}/10 / 신뢰도: {qa_conf}")
            qa_concerns = qa_item.get("concerns", [])
            if qa_concerns:
                sections.append("- 우려 사항:")
                for c in qa_concerns:
                    sections.append(f"  - {c}")
            rec = qa_item.get("recommendation", "")
            if rec:
                sections.append(f"- 권고: {rec}")
        sections.append("")

    # --- Section 6: Feasibility Evidence (LLM-generated) ---
    sections.append("## 6. 실현 가능성 근거")
    feas = feasibility_evidence or {}
    feas_full = feas.get("full_text", "")
    if feas_full:
        sections.append(feas_full)
    else:
        per_topic_feas = feas.get("per_topic", [])
        if per_topic_feas:
            for tf in per_topic_feas:
                if not isinstance(tf, dict):
                    continue
                tid = tf.get("topic_id", "")
                sections.append(f"### {topic_name_by_id.get(tid, tf.get('topic_name', tid))}")
                sections.append(f"- 판정: **{tf.get('verdict', '-')}** ({tf.get('confidence_pct', '-')}%)")
                if tf.get("asset_evidence"):
                    sections.append(f"- 기존 자산: {tf['asset_evidence']}")
                if tf.get("team_capability"):
                    sections.append(f"- 팀 역량: {tf['team_capability']}")
                if tf.get("market_evidence"):
                    sections.append(f"- 시장 근거: {tf['market_evidence']}")
                if tf.get("academic_evidence"):
                    sections.append(f"- 학술 근거: {tf['academic_evidence']}")
            overall = feas.get("overall_portfolio_feasibility", "")
            if overall:
                sections.append("")
                sections.append(f"**포트폴리오 종합:** {overall}")
        else:
            sections.append("- 실현 가능성 근거가 생성되지 않았습니다.")
    sections.append("")

    # --- Section 7: Phase plan (existing) ---
    sections.append("## 7. 구현 권장 로드맵")
    sections.extend(phases_md if phases_md else ["- 해당 토픽의 근거가 부족하여 즉시 실행 불가"])
    sections.append("")

    # --- Section 8: Synergy (existing) ---
    sections.append("## 8. 시너지 추정")
    sections.extend(synergy_lines if synergy_lines else ["- 현재 증거 기반 교집합이 적어 정책/UX/모니터링 레이어 기준으로 간접 연계 권장"])
    sections.append("")

    # --- Section 9: Research sources (existing) ---
    sections.append("## 9. 연구 근거 후보")
    sections.extend(source_lines if source_lines else ["- 연구 출처 후보가 부족함"])
    sections.append("")

    # --- Section 10: Evidence snippets (existing) ---
    sections.append("## 10. 상위 주제 근거 (발췌)")
    sections.extend(evidence_md if evidence_md else ["- 상위 항목 근거가 충분히 수집되지 않음"])
    sections.append("")

    return "\n".join(sections) + "\n\n"


# ---------------------------------------------------------------------------
# JSON report
# ---------------------------------------------------------------------------

def to_json(
    states: dict[str, TopicState],
    scores: dict[str, dict[str, float]],
    scores_initial: dict[str, dict[str, float]] | None,
    ranked: list[dict],
    phases: list[dict],
    report_focus: str,
    version_tag: str,
    research_sources: list[dict[str, str]],
    topic_keywords: dict[str, list[str]] | None = None,
    selected_agent_decisions: dict[str, list[dict]] | None = None,
    discussion: list[dict] | None = None,
    debate_rounds: int = DEBATE_ROUNDS_DEFAULT,
    consensus_summary: dict | None = None,
    orchestration_profile: str = ORCHESTRATION_PROFILE_DEFAULT,
    orchestration_stages: list[str] | None = None,
    service_scope: list[str] | None = None,
    feature_scope: list[str] | None = None,
    pipeline_decisions: list[dict] | list[OrchestrationDecision] | None = None,
    pipeline_stage_log: list[dict] | None = None,
    hierarchical_analysis: dict | None = None,
    strategy_cards_prebuilt: list[dict] | None = None,
    qa_verification: list[dict] | None = None,
    # --- new report sections (LLM-generated) ---
    executive_summary: dict | None = None,
    asis_analysis: dict | None = None,
    tobe_direction: dict | None = None,
    feasibility_evidence: dict | None = None,
    # --- precomputed values (avoid recomputation) ---
    precomputed_agent_rankings: dict[str, list[str]] | None = None,
    precomputed_research_queries: list[dict[str, object]] | None = None,
) -> dict:
    if precomputed_agent_rankings is not None:
        agent_rankings_map = precomputed_agent_rankings
    else:
        agent_rankings_map = build_agent_rankings(scores, top_k=max(1, len(ranked)))
    consensus = []
    if consensus_summary:
        consensus = list(consensus_summary.get("final_consensus_ids", []))
    if precomputed_research_queries is not None:
        research_queries = precomputed_research_queries
    else:
        from .research import build_research_queries
        research_queries = build_research_queries(ranked, topic_keywords=topic_keywords, top_k=min(6, len(ranked)))
    selected = ranked[:len(ranked)]
    agent_decisions = selected_agent_decisions or {}
    orchestration_stages = _normalize_stages(orchestration_stages, fallback=ORCHESTRATION_STAGES_DEFAULT)
    pipeline_decisions = pipeline_decisions or []
    stage_log = pipeline_stage_log or []
    decision_records = [
        decision.to_dict() if isinstance(decision, OrchestrationDecision) else dict(decision)
        for decision in pipeline_decisions
    ]
    strategy_cards = strategy_cards_prebuilt or _build_minimal_cards(selected, states, agent_decisions, research_sources)
    result = {
        "report_version": version_tag,
        "report_focus": report_focus,
        "generated_at": dt.datetime.now().isoformat(),
        "topics": [states[k].to_dict() for k in sorted(states)],
        "research_sources": research_sources,
        "agent_scores": scores,
        "agent_scores_initial": scores_initial or scores,
        "debate_rounds_requested": debate_rounds,
        "debate_rounds_executed": len(discussion or []),
        "discussion": discussion or [],
        "strategy_cards": strategy_cards,
        "qa_verification": qa_verification or [],
        "agent_rankings": agent_rankings_map,
        "agent_decisions": agent_decisions,
        "consensus": consensus,
        "consensus_summary": consensus_summary,
        "research_queries": research_queries,
        "ranked": ranked,
        "phases": phases,
        "orchestration": {
            "profile": orchestration_profile,
            "stages": orchestration_stages,
            "service_scope": service_scope or [],
            "feature_scope": feature_scope or [],
            "pipeline_decisions": decision_records,
            "stage_log": stage_log,
        },
    }
    # New LLM-generated report sections (preserved in JSON)
    if executive_summary:
        result["executive_summary"] = executive_summary
    if asis_analysis:
        result["asis_analysis"] = asis_analysis
    if tobe_direction:
        result["tobe_direction"] = tobe_direction
    if feasibility_evidence:
        result["feasibility_evidence"] = feasibility_evidence
    if hierarchical_analysis:
        result["hierarchical_analysis"] = hierarchical_analysis

    # Section completion metadata — tells consumers which LLM sections succeeded
    result["section_status"] = {
        "executive_summary": "ok" if executive_summary else "skipped",
        "asis_analysis": "ok" if asis_analysis else "skipped",
        "tobe_direction": "ok" if tobe_direction else "skipped",
        "feasibility_evidence": "ok" if feasibility_evidence else "skipped",
        "strategy_cards": "ok" if strategy_cards_prebuilt else "fallback",
        "qa_verification": "ok" if qa_verification else "skipped",
    }
    return result
